homebrew_installed_packages:
  - autoconf
  - ca-certificates
  - curl
  - git
  - go
  - gpg
  - httpie
  - iperf
  - jq
  - libevent
  - mackup
  - node
  - nvm
  - openssl
  - python
  - ssh-copy-id
  - thefuck
  - tmux
  - wget
  - wifi-password
  - zsh
  - zsh-history-substring-search
  - zstd

homebrew_cask_apps:
  - 1password
  - appcleaner
  - dropbox
  - gitkraken
  - hyper
  - lunar
  - microsoft-teams
  - moom
  - onyx
  - postman
  - raycast
  - slack
  - stats
  - the-unarchiver
  - unclack
  - warp

npm_packages:
  - name: http-server
  - name: npm
  - name: prettier
  - name: typescript
  - name: webpack
  - name: yarn

configure_dock: true
dockitems_remove:
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Pages
  - Numbers
  - Keynote
  - Books
dockitems_persist:
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
  - name: "Warp"
    path: "/Applications/Warp.app/"
  - name: "GitKraken"
    path: "/Applications/GitKraken.app"
  - name: "Postman"
    path: "/Applications/Postman.app"
